[tool.pyright]
reportMissingImports = "none"
reportMissingModuleSource = "none" 
reportOptionalSubscript = "none"
reportOptionalMemberAccess = "none"
reportOptionalCall = "none"
reportOptionalIterable = "none"
reportOptionalContextManager = "none"
reportOptionalOperand = "none"
reportTypedDictNotRequiredAccess = "none"
reportUnknownMemberType = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUnknownParameterType = "none"
reportMissingParameterType = "none"
reportMissingTypeArgument = "none"
reportInvalidTypeVarUse = "none"
reportCallInDefaultInitializer = "none"
reportUnnecessaryIsInstance = "none"
reportUnnecessaryCast = "none"
reportUnnecessaryComparison = "none"
reportUnnecessaryContains = "none"
reportImplicitStringConcatenation = "none"
reportUndefinedVariable = "none"
strictListInference = false
strictDictionaryInference = false
strictSetInference = false
pythonVersion = "3.11"
typeCheckingMode = "off"

[tool.basedpyright]
reportMissingImports = "none"
reportMissingModuleSource = "none"
reportOptionalSubscript = "none"
reportOptionalMemberAccess = "none"
reportOptionalCall = "none"
reportOptionalIterable = "none"
reportOptionalContextManager = "none"
reportOptionalOperand = "none"
reportTypedDictNotRequiredAccess = "none"
reportUnknownMemberType = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUnknownParameterType = "none"
reportMissingParameterType = "none"
reportMissingTypeArgument = "none"
reportInvalidTypeVarUse = "none"
reportCallInDefaultInitializer = "none"
reportUnnecessaryIsInstance = "none"
reportUnnecessaryCast = "none"
reportUnnecessaryComparison = "none"
reportUnnecessaryContains = "none"
reportImplicitStringConcatenation = "none"
reportUndefinedVariable = "none"
strictListInference = false
strictDictionaryInference = false
strictSetInference = false
pythonVersion = "3.11"
typeCheckingMode = "off"